spring:
  profiles:
    active: dev
---
server:
  port: 8001
mybatis:
  config-location: classpath:mybatis/mybatis_config.xml
  type-aliases-package: cn.zzsxt.springcloud.entity
  mapper-locations: classpath:mybatis/mapper/**/*.xml
spring:
  profiles: dev
  application:
    name: springcloud-provider-dept
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://localhost:3306/springcloud
    username: root
    password: root
    dbcp2:
      min-idle: 5    #数据库最小维持链接数
      initial-size: 5 #初始化连接数
      max-total: 5 #最大链接数
      max-conn-lifetime-millis: 200 #等待链接获得的最大超时时间
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/
  instance:
    instance-id: microservicecloud-dept8001
    prefer-ip-address: true    #访问路径可以显示ip地址
info:
  app.name: 部门管理
  company.name: www.zzsxt.cn
  build.artifactId: $project.artifactId$
  build.version: $project.version$


---
server:
  port: 8002
mybatis:
  config-location: classpath:mybatis/mybatis_config.xml
  type-aliases-package: cn.zzsxt.springcloud.entity
  mapper-locations: classpath:mybatis/mapper/**/*.xml
spring:
  profiles: test
  application:
    name: springcloud-provider-dept
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://localhost:3306/springcloud2
    username: root
    password: root
    dbcp2:
      min-idle: 5    #数据库最小维持链接数
      initial-size: 5 #初始化连接数
      max-total: 5 #最大链接数
      max-conn-lifetime-millis: 200 #等待链接获得的最大超时时间
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/
  instance:
    instance-id: microservicecloud-dept8002
    prefer-ip-address: true    #访问路径可以显示ip地址
info:
  app.name: 部门管理
  company.name: www.zzsxt.cn
  build.artifactId: $project.artifactId$
  build.version: $project.version$